In [142]:
import numpy as np
import pandas as pd

In [143]:
np.full(5, 8.1)

array([8.1, 8.1, 8.1, 8.1, 8.1])

In [ ]:
a = np.array([1, 2, 3, 4, 5, 6])

In [145]:
a

array([1, 2, 3, 4, 5, 6])

In [146]:
a[2] = 1000

In [147]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [ ]:
np.linspace(1, 10, 10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.zeros((2, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
n = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [ ]:
n[1, 1] = 50

In [153]:
n

array([[ 1,  2,  3],
       [ 4, 50,  6],
       [ 7,  8,  9]])

In [ ]:
n[1] = [1, 1, 1]

In [155]:
n

array([[1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

n[:,1] = [1,1,1]


In [156]:
n

array([[1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

In [ ]:
np.random.rand(3, 4)

array([[0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812],
       [0.18443987, 0.78533515, 0.85397529, 0.49423684]])

In [ ]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [ ]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]], dtype=int32)

In [160]:
a[2] = 3

In [161]:
a + 1

array([2, 3, 4, 5, 6, 7])

In [162]:
a

array([1, 2, 3, 4, 5, 6])

In [ ]:
b = np.array([1, 1, 1, 1, 1, 1])

In [164]:
b

array([1, 1, 1, 1, 1, 1])

In [165]:
a.shape[0]

6

In [ ]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result += u[i] * v[i]
    return result

In [ ]:
vector_vector_multiplication(a, b)

np.float64(21.0)

In [168]:
a.dot(b)

np.int64(21)

In [ ]:
C = np.ones((2, 3))

In [170]:
C

array([[1., 1., 1.],
       [1., 1., 1.]])

In [171]:
d = np.ones(3)

In [ ]:
def matrix_vector_multiplication(c, d):
    assert c.shape[1] == d.shape[0]
    m = c.shape[0]
    result = np.zeros(m)
    for i in range(m):
        result[i] = vector_vector_multiplication(C[i], d)
    return result

In [ ]:
matrix_vector_multiplication(C, d)

array([3., 3.])

In [174]:
C.dot(d)

array([3., 3.])

In [ ]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]

    num_rows = U.shape[0]
    num_cols = V.shape[1]

    result = np.zeros((num_rows, num_cols))

    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi

    return result

In [176]:
I = np.eye(4)

In [ ]:
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
I[0, 1]

np.float64(0.0)

In [179]:
n

array([[1, 2, 3],
       [1, 1, 1],
       [7, 8, 9]])

In [ ]:
V = np.array(
    [
        [1, 1, 2],
        [0, 0.5, 1],
        [0, 2, 1],
    ]
)

In [181]:
inv = np.linalg.inv(V)

In [182]:
inv.dot(V)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [183]:
inv

array([[ 1.        , -2.        ,  0.        ],
       [ 0.        , -0.66666667,  0.66666667],
       [ 0.        ,  1.33333333, -0.33333333]])

Data Frames


In [ ]:
data = [
    ["Nissan", "Stanza", 1991, 138, 4, "MANUAL", "sedan", 2000],
    ["Hyundai", "Sonata", 2017, None, 4, "AUTOMATIC", "Sedan", 27150],
    ["Lotus", "Elise", 2010, 218, 4, "MANUAL", "convertible", 54990],
    ["GMC", "Acadia", 2017, 194, 4, "AUTOMATIC", "4dr SUV", 34450],
    ["Nissan", "Frontier", 2017, 261, 6, "MANUAL", "Pickup", 32340],
]

columns = [
    "Make",
    "Model",
    "Year",
    "Engine HP",
    "Engine Cylinders",
    "Transmission Type",
    "Vehicle_Style",
    "MSRP",
]

In [191]:
df = pd.DataFrame(data, columns=columns)
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [ ]:
data2 = [
    {
        "Make": "Nissan",
        "Model": "Stanza",
        "Year": 1991,
        "Engine HP": 138.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "sedan",
        "MSRP": 2000,
    },
    {
        "Make": "Hyundai",
        "Model": "Sonata",
        "Year": 2017,
        "Engine HP": "None",
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "Sedan",
        "MSRP": 27150,
    },
    {
        "Make": "Lotus",
        "Model": "Elise",
        "Year": 2010,
        "Engine HP": 218.0,
        "Engine Cylinders": 4,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "convertible",
        "MSRP": 54990,
    },
    {
        "Make": "GMC",
        "Model": "Acadia",
        "Year": 2017,
        "Engine HP": 194.0,
        "Engine Cylinders": 4,
        "Transmission Type": "AUTOMATIC",
        "Vehicle_Style": "4dr SUV",
        "MSRP": 34450,
    },
    {
        "Make": "Nissan",
        "Model": "Frontier",
        "Year": 2017,
        "Engine HP": 261.0,
        "Engine Cylinders": 6,
        "Transmission Type": "MANUAL",
        "Vehicle_Style": "Pickup",
        "MSRP": 32340,
    },
]

In [207]:
pd.DataFrame(data2)

Make     Model  Year Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991     138.0                 4            MANUAL   
1  Hyundai    Sonata  2017      None                 4         AUTOMATIC   
2    Lotus     Elise  2010     218.0                 4            MANUAL   
3      GMC    Acadia  2017     194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017     261.0                 6            MANUAL   

  Vehicle_Style   MSRP  
0         sedan   2000  
1         Sedan  27150  
2   convertible  54990  
3       4dr SUV  34450  
4        Pickup  32340

In [208]:
df.head(n=2)

Make   Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan  Stanza  1991      138.0                 4            MANUAL   
1  Hyundai  Sonata  2017        NaN                 4         AUTOMATIC   

  Vehicle_Style   MSRP country  
0         sedan   2000   japan  
1         Sedan  27150   korea

In [ ]:
df[["Engine HP", "Make"]]

Engine HP     Make
0      138.0   Nissan
1        NaN  Hyundai
2      218.0    Lotus
3      194.0      GMC
4      261.0   Nissan

In [ ]:
df["country"] = ["japan", "korea", "uk", "usa", "Nigeria"]

In [213]:
df

Make     Model  Year  Engine HP  Engine Cylinders Transmission Type  \
0   Nissan    Stanza  1991      138.0                 4            MANUAL   
1  Hyundai    Sonata  2017        NaN                 4         AUTOMATIC   
2    Lotus     Elise  2010      218.0                 4            MANUAL   
3      GMC    Acadia  2017      194.0                 4         AUTOMATIC   
4   Nissan  Frontier  2017      261.0                 6            MANUAL   

  Vehicle_Style   MSRP  country  
0         sedan   2000    japan  
1         Sedan  27150    korea  
2   convertible  54990       uk  
3       4dr SUV  34450      usa  
4        Pickup  32340  Nigeria

In [ ]:
del df["Engine Cylinders"]

In [215]:
df

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
0   Nissan    Stanza  1991      138.0            MANUAL         sedan   2000   
1  Hyundai    Sonata  2017        NaN         AUTOMATIC         Sedan  27150   
2    Lotus     Elise  2010      218.0            MANUAL   convertible  54990   
3      GMC    Acadia  2017      194.0         AUTOMATIC       4dr SUV  34450   
4   Nissan  Frontier  2017      261.0            MANUAL        Pickup  32340   

   country  
0    japan  
1    korea  
2       uk  
3      usa  
4  Nigeria

In [ ]:
df.index = ["a", "b", "c", "d", "e"]

In [ ]:
df

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
a   Nissan    Stanza  1991      138.0            MANUAL         sedan   2000   
b  Hyundai    Sonata  2017        NaN         AUTOMATIC         Sedan  27150   
c    Lotus     Elise  2010      218.0            MANUAL   convertible  54990   
d      GMC    Acadia  2017      194.0         AUTOMATIC       4dr SUV  34450   
e   Nissan  Frontier  2017      261.0            MANUAL        Pickup  32340   

   country  
a    japan  
b    korea  
c       uk  
d      usa  
e  Nigeria

In [ ]:
df.loc[["a", "b"]]

Make   Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
a   Nissan  Stanza  1991      138.0            MANUAL         sedan   2000   
b  Hyundai  Sonata  2017        NaN         AUTOMATIC         Sedan  27150   

  country  
a   japan  
b   korea

In [ ]:
df.iloc[[0, 1, 2]]

Make   Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
a   Nissan  Stanza  1991      138.0            MANUAL         sedan   2000   
b  Hyundai  Sonata  2017        NaN         AUTOMATIC         Sedan  27150   
c    Lotus   Elise  2010      218.0            MANUAL   convertible  54990   

  country  
a   japan  
b   korea  
c      uk

In [236]:
df = df.reset_index(drop=True)
df

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
0   Nissan    Stanza  1991      138.0            MANUAL         sedan   2000   
1  Hyundai    Sonata  2017        NaN         AUTOMATIC         Sedan  27150   
2    Lotus     Elise  2010      218.0            MANUAL   convertible  54990   
3      GMC    Acadia  2017      194.0         AUTOMATIC       4dr SUV  34450   
4   Nissan  Frontier  2017      261.0            MANUAL        Pickup  32340   

   country  
0    japan  
1    korea  
2       uk  
3      usa  
4  Nigeria

In [ ]:
df["Year"] >= 2015

0    False
1     True
2    False
3     True
4     True
Name: Year, dtype: bool

In [ ]:
df[df["Year"] >= 2015]

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
1  Hyundai    Sonata  2017        NaN         AUTOMATIC         Sedan  27150   
3      GMC    Acadia  2017      194.0         AUTOMATIC       4dr SUV  34450   
4   Nissan  Frontier  2017      261.0            MANUAL        Pickup  32340   

   country  
1    korea  
3      usa  
4  Nigeria

In [250]:
df[(df["Year"] >= 2015) & (df["Make"] == "Nissan")]

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
4  Nissan  Frontier  2017      261.0            MANUAL        Pickup  32340   

   country  
4  Nigeria

In [252]:
df["Vehicle_Style"].str.lower()

0          sedan
1          sedan
2    convertible
3        4dr suv
4         pickup
Name: Vehicle_Style, dtype: object

In [ ]:
df["Vehicle_Style"] = df["Vehicle_Style"].str.replace(" ", "_").str.lower()
df["Vehicle_Style"]

0          sedan
1          sedan
2    convertible
3        4dr_suv
4         pickup
Name: Vehicle_Style, dtype: object

In [256]:
df.to_dict(orient="records")

[{'Make': 'Nissan',
  'Model': 'Stanza',
  'Year': 1991,
  'Engine HP': 138.0,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'sedan',
  'MSRP': 2000,
  'country': 'japan'},
 {'Make': 'Hyundai',
  'Model': 'Sonata',
  'Year': 2017,
  'Engine HP': nan,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': 'sedan',
  'MSRP': 27150,
  'country': 'korea'},
 {'Make': 'Lotus',
  'Model': 'Elise',
  'Year': 2010,
  'Engine HP': 218.0,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'convertible',
  'MSRP': 54990,
  'country': 'uk'},
 {'Make': 'GMC',
  'Model': 'Acadia',
  'Year': 2017,
  'Engine HP': 194.0,
  'Transmission Type': 'AUTOMATIC',
  'Vehicle_Style': '4dr_suv',
  'MSRP': 34450,
  'country': 'usa'},
 {'Make': 'Nissan',
  'Model': 'Frontier',
  'Year': 2017,
  'Engine HP': 261.0,
  'Transmission Type': 'MANUAL',
  'Vehicle_Style': 'pickup',
  'MSRP': 32340,
  'country': 'Nigeria'}]

In [261]:
df

Make     Model  Year  Engine HP Transmission Type Vehicle_Style   MSRP  \
0   Nissan    Stanza  1991      138.0            MANUAL         sedan   2000   
1  Hyundai    Sonata  2017        NaN         AUTOMATIC         sedan  27150   
2    Lotus     Elise  2010      218.0            MANUAL   convertible  54990   
3      GMC    Acadia  2017      194.0         AUTOMATIC       4dr_suv  34450   
4   Nissan  Frontier  2017      261.0            MANUAL        pickup  32340   

   country  
0    japan  
1    korea  
2       uk  
3      usa  
4  Nigeria

In [260]:
df.groupby("Make").MSRP.max()

Make
GMC        34450
Hyundai    27150
Lotus      54990
Nissan     32340
Name: MSRP, dtype: int64

In [264]:
df.nunique()

Make                 4
Model                5
Year                 3
Engine HP            4
Transmission Type    2
Vehicle_Style        4
MSRP                 5
country              5
dtype: int64

In [266]:

df.describe().round(2)

Year  Engine HP      MSRP
count     5.00       4.00      5.00
mean   2010.40     202.75  30186.00
std      11.26      51.30  18985.04
min    1991.00     138.00   2000.00
25%    2010.00     180.00  27150.00
50%    2017.00     206.00  32340.00
75%    2017.00     228.75  34450.00
max    2017.00     261.00  54990.00

In [272]:
df.isnull()


Make  Model   Year  Engine HP  Transmission Type  Vehicle_Style   MSRP  \
0  False  False  False      False              False          False  False   
1  False  False  False       True              False          False  False   
2  False  False  False      False              False          False  False   
3  False  False  False      False              False          False  False   
4  False  False  False      False              False          False  False   

   country  
0    False  
1    False  
2    False  
3    False  
4    False